package com.vme.gzh.domain;

import java.io.Serializable;
import java.util.Date;

public class ChatUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.userId
     *
     * @mbggenerated Sun Aug 28 15:44:34 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.userName
     *
     * @mbggenerated Sun Aug 28 15:44:34 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.passWord
     *
     * @mbggenerated Sun Aug 28 15:44:34 CST 2016
     */
    private String passWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.loginTime
     *
     * @mbggenerated Sun Aug 28 15:44:34 CST 2016
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_user
     *
     * @mbggenerated Sun Aug 28 15:44:34 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Sun Aug 28 15:44:34 CST 2016
     */
    public ChatUser(Integer userId, String userName, String passWord, Date loginTime) {
        this.userId = userId;
        this.userName = userName;
        this.passWord = passWord;
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.userId
     *
     * @return the value of tb_user.userId
     *
     * @mbggenerated Sun Aug 28 15:44:34 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.userName
     *
     * @return the value of tb_user.userName
     *
     * @mbggenerated Sun Aug 28 15:44:34 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.passWord
     *
     * @return the value of tb_user.passWord
     *
     * @mbggenerated Sun Aug 28 15:44:34 CST 2016
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.loginTime
     *
     * @return the value of tb_user.loginTime
     *
     * @mbggenerated Sun Aug 28 15:44:34 CST 2016
     */
    public Date getLoginTime() {
        return loginTime;
    }
}