package com.vme.gzh.dao;

import com.vme.gzh.domain.ChatUser;
import org.springframework.stereotype.Repository;

import java.util.Map;

@Repository
public interface ChatUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Sun Aug 28 15:44:34 CST 2016
     */
    int insert(ChatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Sun Aug 28 15:44:34 CST 2016
     */
    int insertSelective(ChatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Sun Aug 28 15:44:34 CST 2016
     */
    ChatUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Sun Aug 28 15:44:34 CST 2016
     */
    int updateByPrimaryKeySelective(ChatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Sun Aug 28 15:44:34 CST 2016
     */
    int updateByPrimaryKey(ChatUser record);

    ChatUser login(Map map);
}